<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>main</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="air_pollutioni_files/libs/clipboard/clipboard.min.js"></script>
<script src="air_pollutioni_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="air_pollutioni_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="air_pollutioni_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="air_pollutioni_files/libs/quarto-html/popper.min.js"></script>
<script src="air_pollutioni_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="air_pollutioni_files/libs/quarto-html/anchor.min.js"></script>
<link href="air_pollutioni_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="air_pollutioni_files/libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="air_pollutioni_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="air_pollutioni_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="air_pollutioni_files/libs/bootstrap/bootstrap-a5a9fd141f258f2edafef5ad22a6997f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">main</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>✔ ggplot2 4.0.0     ✔ purrr   1.1.0
✔ tibble  3.3.0     ✔ dplyr   1.1.4
✔ tidyr   1.3.1     ✔ stringr 1.5.2
✔ readr   2.1.5     ✔ forcats 0.5.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ purrr::%||%()   masks base::%||%()
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'lubridate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    date, intersect, setdiff, union</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forecast)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    some</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(boot)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'boot'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:car':

    logit</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>cities <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"New York"</span>, <span class="st">"Los Angeles"</span>, <span class="st">"Chicago"</span>, <span class="st">"Houston"</span>, <span class="st">"Phoenix"</span>,</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Philadelphia"</span>, <span class="st">"San Antonio"</span>, <span class="st">"San Diego"</span>, <span class="st">"Dallas"</span>, <span class="st">"San Jose"</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>pm25_raw <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/daily_88101_2023.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 847057 Columns: 29
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (16): State Code, County Code, Site Num, Datum, Parameter Name, Sample ...
dbl  (11): Parameter Code, POC, Latitude, Longitude, Observation Count, Obse...
date  (2): Date Local, Date of Last Change

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>o3_raw   <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/daily_44201_2023.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 388292 Columns: 29
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (17): State Code, County Code, Site Num, Datum, Parameter Name, Sample ...
dbl  (10): Parameter Code, POC, Latitude, Longitude, Observation Count, Obse...
date  (2): Date Local, Date of Last Change

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>no2_raw  <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/daily_42602_2023.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 156472 Columns: 29
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (17): State Code, County Code, Site Num, Datum, Parameter Name, Sample ...
dbl  (10): Parameter Code, POC, Latitude, Longitude, Observation Count, Obse...
date  (2): Date Local, Date of Last Change

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>clean_pollutant <span class="ot">&lt;-</span> <span class="cf">function</span>(df, pollutant_name) {</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  df <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="st">`</span><span class="at">City Name</span><span class="st">`</span> <span class="sc">%in%</span> cities) <span class="sc">%&gt;%</span>          <span class="co"># filter ROWS by city name</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Date =</span> <span class="fu">ymd</span>(<span class="st">`</span><span class="at">Date Local</span><span class="st">`</span>)) <span class="sc">%&gt;%</span>         <span class="co"># convert date</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="st">`</span><span class="at">City Name</span><span class="st">`</span>, Date, <span class="st">`</span><span class="at">Arithmetic Mean</span><span class="st">`</span>) <span class="sc">%&gt;%</span>  <span class="co"># select correct columns</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rename</span>(</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">City =</span> <span class="st">`</span><span class="at">City Name</span><span class="st">`</span>,</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>      <span class="sc">!!</span><span class="at">pollutant_name :=</span> <span class="st">`</span><span class="at">Arithmetic Mean</span><span class="st">`</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>pm25 <span class="ot">&lt;-</span> <span class="fu">clean_pollutant</span>(pm25_raw, <span class="st">"PM25"</span>)</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>o3   <span class="ot">&lt;-</span> <span class="fu">clean_pollutant</span>(o3_raw,   <span class="st">"O3"</span>)</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>no2  <span class="ot">&lt;-</span> <span class="fu">clean_pollutant</span>(no2_raw,  <span class="st">"NO2"</span>)</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>air_df <span class="ot">&lt;-</span> pm25 <span class="sc">%&gt;%</span></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(o3, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"City"</span>, <span class="st">"Date"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(no2, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"City"</span>, <span class="st">"Date"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in inner_join(., o3, by = c("City", "Date")): Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 1 of `x` matches multiple rows in `y`.
ℹ Row 12 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in inner_join(., no2, by = c("City", "Date")): Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 1 of `x` matches multiple rows in `y`.
ℹ Row 12 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># There are duplicate rows as the indicators have multiple monitoring sites per city. </span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>air_df_clean <span class="ot">&lt;-</span> air_df <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(City, Date) <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">PM25 =</span> <span class="fu">mean</span>(PM25, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">O3   =</span> <span class="fu">mean</span>(O3,   <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">NO2  =</span> <span class="fu">mean</span>(NO2,  <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(City, Date)</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(air_df_clean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 3,367
Columns: 5
$ City &lt;chr&gt; "Chicago", "Chicago", "Chicago", "Chicago", "Chicago", "Chicago",…
$ Date &lt;date&gt; 2023-03-01, 2023-03-02, 2023-03-04, 2023-03-07, 2023-03-10, 2023…
$ PM25 &lt;dbl&gt; 9.166667, 2.800000, 16.100000, 3.150000, 3.300000, 4.175000, 10.8…
$ O3   &lt;dbl&gt; 0.02643133, 0.03649033, 0.02109800, 0.03809800, 0.03385300, 0.032…
$ NO2  &lt;dbl&gt; 15.797916, 9.470833, 19.579167, 6.368750, 10.012500, 11.920265, 1…</code></pre>
</div>
</div>
<p>3,367 instead of 3,650 because some cities have missing days, some monitoring stations fail to record, etc.</p>
<p>Now, Time-series EDA in R</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>city_name <span class="ot">&lt;-</span> <span class="st">"Los Angeles"</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>la_df <span class="ot">&lt;-</span> air_df <span class="sc">%&gt;%</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(City <span class="sc">==</span> city_name) <span class="sc">%&gt;%</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Date)</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>la_long <span class="ot">&lt;-</span> la_df <span class="sc">%&gt;%</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(PM25, O3, NO2),</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"Pollutant"</span>,</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"Value"</span>)</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>la_long <span class="ot">&lt;-</span> air_df_clean <span class="sc">%&gt;%</span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(City <span class="sc">==</span> <span class="st">"Los Angeles"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(PM25, O3, NO2),</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"Pollutant"</span>,</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"Value"</span>)</span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(la_long, <span class="fu">aes</span>(<span class="at">x =</span> Date, <span class="at">y =</span> Value)) <span class="sc">+</span></span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Pollutant, <span class="at">scales =</span> <span class="st">"free_y"</span>, <span class="at">ncol =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Daily Pollution Levels in Los Angeles (2023)"</span>,</span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Date"</span>,</span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Concentration"</span></span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">14</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="air_pollutioni_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Hypothesis Testing</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>air_df <span class="ot">&lt;-</span> air_df <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Region =</span> <span class="fu">case_when</span>(</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>      City <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"New York"</span>, <span class="st">"Philadelphia"</span>) <span class="sc">~</span> <span class="st">"East"</span>,</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>      City <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Los Angeles"</span>, <span class="st">"San Diego"</span>) <span class="sc">~</span> <span class="st">"West"</span>,</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Other"</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>east_pm25 <span class="ot">&lt;-</span> air_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Region <span class="sc">==</span> <span class="st">"East"</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(PM25)</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>west_pm25 <span class="ot">&lt;-</span> air_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Region <span class="sc">==</span> <span class="st">"West"</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(PM25)</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(east_pm25, west_pm25, <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  east_pm25 and west_pm25
t = 26.974, df = 95424, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 1.282018 1.482925
sample estimates:
mean of x mean of y 
11.224595  9.842124 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">sample</span>(east_pm25, <span class="dv">500</span>))  </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  sample(east_pm25, 500)
W = 0.37979, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">sample</span>(west_pm25, <span class="dv">500</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  sample(west_pm25, 500)
W = 0.91917, p-value = 1.015e-15</code></pre>
</div>
</div>
<p>Both p-values are way below 0.05, so we reject the null hypothesis of normality. both distributions are not normally distributed. So we can’t trust a standard t-test, so instead we will use Wilcoxon rank-sum test.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(east_pm25, west_pm25)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  east_pm25 and west_pm25
W = 1543844876, p-value &lt; 2.2e-16
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>Since the p-value is way below 0.05, you reject the null hypothesis and this tells us there is a statistically significant evidence that PM2.5 levels between East and West cities are different. We can see the median values to see which region has higher PM2.5:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(east_pm25, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.345833</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(west_pm25, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.945</code></pre>
</div>
</div>
<p>The difference is not huge it is slight, but with the wildfires, we would expect this same pattern and even more exacerbated that the west has higher pm25 levels.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check equal variances first</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(PM25 <span class="sc">~</span> City, <span class="at">data =</span> air_df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in leveneTest.default(y = y, group = group, ...): group coerced to
factor.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
          Df F value    Pr(&gt;F)    
group      9    1096 &lt; 2.2e-16 ***
      723666                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>anova_fit <span class="ot">&lt;-</span> <span class="fu">aov</span>(PM25 <span class="sc">~</span> City, <span class="at">data =</span> air_df)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Df   Sum Sq Mean Sq F value Pr(&gt;F)    
City             9  1080252  120028    1877 &lt;2e-16 ***
Residuals   723666 46269984      64                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The null hypothesis tells us that Levene’s test is testing that all groups have equal variances. Since the p value is way below 0.05, we reject the null hypothesis which means variances differ significantly across the 10 cities. Homogeniety of variances is violated.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(PM25 <span class="sc">~</span> City, <span class="at">data =</span> air_df_clean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  PM25 by City
Kruskal-Wallis chi-squared = 325.67, df = 9, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Because both normality and equal variances assumptions were violated, we used Kruskal-Wallis test to compare PM2.5 levels across the ten major cities. The test is showing a highly significant result as the p-value is way below 0.05. This shows then that the PM2.5 concentration levels differ substantially across these cities. There is a meaningful variation in urban air quality patterns across the country.</p>
<p>now testing for ozone across all 10 cities as we did for PM2.5.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(O3 <span class="sc">~</span> City, <span class="at">data =</span> air_df_clean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in leveneTest.default(y = y, group = group, ...): group coerced to
factor.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
        Df F value    Pr(&gt;F)    
group    9  22.682 &lt; 2.2e-16 ***
      3357                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Same as PM2.5, p-value is less than 0.05 so ANOVA assumption is violated, we must use kruskal-wallis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>anova_o3 <span class="ot">&lt;-</span> <span class="fu">aov</span>(O3 <span class="sc">~</span> City, <span class="at">data =</span> air_df_clean)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_o3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Df Sum Sq   Mean Sq F value Pr(&gt;F)    
City           9 0.0258 0.0028650   27.73 &lt;2e-16 ***
Residuals   3357 0.3468 0.0001033                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The p-value here is small so although evidence may show O3 levels vary across cities, we can’t trust ANOVA since the assumptions were violated.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(O3 <span class="sc">~</span> City, <span class="at">data =</span> air_df_clean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  O3 by City
Kruskal-Wallis chi-squared = 238.47, df = 9, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>P-value is also way below 0.05, so median O3 levels differ significantly across cities.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>la_o3 <span class="ot">&lt;-</span> air_df_clean <span class="sc">%&gt;%</span> <span class="fu">filter</span>(City <span class="sc">==</span> <span class="st">"Los Angeles"</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(O3)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>ny_o3 <span class="ot">&lt;-</span> air_df_clean <span class="sc">%&gt;%</span> <span class="fu">filter</span>(City <span class="sc">==</span> <span class="st">"New York"</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(O3)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(la_o3, ny_o3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  la_o3 and ny_o3
W = 74658, p-value = 0.004743
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  air_df_clean<span class="sc">$</span>O3[air_df_clean<span class="sc">$</span>City <span class="sc">==</span> <span class="st">"Los Angeles"</span>],</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  air_df_clean<span class="sc">$</span>O3[air_df_clean<span class="sc">$</span>City <span class="sc">==</span> <span class="st">"New York"</span>]</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  air_df_clean$O3[air_df_clean$City == "Los Angeles"] and air_df_clean$O3[air_df_clean$City == "New York"]
W = 74658, p-value = 0.004743
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>air_df_clean <span class="sc">%&gt;%</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(City) <span class="sc">%&gt;%</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">median_O3 =</span> <span class="fu">median</span>(O3, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(median_O3))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   City         median_O3
   &lt;chr&gt;            &lt;dbl&gt;
 1 Chicago         0.0345
 2 Phoenix         0.0335
 3 San Diego       0.0324
 4 Dallas          0.0320
 5 Los Angeles     0.0305
 6 San Antonio     0.0290
 7 Philadelphia    0.0290
 8 New York        0.0272
 9 San Jose        0.0258
10 Houston         0.0248</code></pre>
</div>
</div>
<p>For NO2:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(NO2 <span class="sc">~</span> City, <span class="at">data =</span> air_df_clean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in leveneTest.default(y = y, group = group, ...): group coerced to
factor.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
        Df F value    Pr(&gt;F)    
group    9  25.228 &lt; 2.2e-16 ***
      3357                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>anova_no2 <span class="ot">&lt;-</span> <span class="fu">aov</span>(NO2 <span class="sc">~</span> City, <span class="at">data =</span> air_df_clean)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_no2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Df Sum Sq Mean Sq F value Pr(&gt;F)    
City           9  38529    4281     132 &lt;2e-16 ***
Residuals   3357 108905      32                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(NO2 <span class="sc">~</span> City, <span class="at">data =</span> air_df_clean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  NO2 by City
Kruskal-Wallis chi-squared = 1064.3, df = 9, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(boot)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>la_ny_pm25 <span class="ot">&lt;-</span> air_df_clean <span class="sc">%&gt;%</span></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(City <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Los Angeles"</span>, <span class="st">"New York"</span>))</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>boot_stat_pm25 <span class="ot">&lt;-</span> <span class="cf">function</span>(data, indices) {</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>  d <span class="ot">&lt;-</span> data[indices, ]</span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>  mean_la  <span class="ot">&lt;-</span> <span class="fu">mean</span>(d<span class="sc">$</span>PM25[d<span class="sc">$</span>City <span class="sc">==</span> <span class="st">"Los Angeles"</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a>  mean_ny  <span class="ot">&lt;-</span> <span class="fu">mean</span>(d<span class="sc">$</span>PM25[d<span class="sc">$</span>City <span class="sc">==</span> <span class="st">"New York"</span>],   <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a>  mean_la <span class="sc">-</span> mean_ny</span>
<span id="cb70-11"><a href="#cb70-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb70-12"><a href="#cb70-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-13"><a href="#cb70-13" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb70-14"><a href="#cb70-14" aria-hidden="true" tabindex="-1"></a>boot_res_pm25 <span class="ot">&lt;-</span> <span class="fu">boot</span>(<span class="at">data =</span> la_ny_pm25,</span>
<span id="cb70-15"><a href="#cb70-15" aria-hidden="true" tabindex="-1"></a>                      <span class="at">statistic =</span> boot_stat_pm25,</span>
<span id="cb70-16"><a href="#cb70-16" aria-hidden="true" tabindex="-1"></a>                      <span class="at">R =</span> <span class="dv">2000</span>)</span>
<span id="cb70-17"><a href="#cb70-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-18"><a href="#cb70-18" aria-hidden="true" tabindex="-1"></a>boot_res_pm25</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
ORDINARY NONPARAMETRIC BOOTSTRAP


Call:
boot(data = la_ny_pm25, statistic = boot_stat_pm25, R = 2000)


Bootstrap Statistics :
    original      bias    std. error
t1* 1.381574 -0.01600201   0.6898628</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boot.ci</span>(boot_res_pm25, <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"perc"</span>, <span class="st">"bca"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>BOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS
Based on 2000 bootstrap replicates

CALL : 
boot.ci(boot.out = boot_res_pm25, type = c("perc", "bca"))

Intervals : 
Level     Percentile            BCa          
95%   (-0.096,  2.615 )   (-0.418,  2.450 )  
Calculations and Intervals on Original Scale</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>la_ny_o3 <span class="ot">&lt;-</span> air_df_clean <span class="sc">%&gt;%</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(City <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Los Angeles"</span>, <span class="st">"New York"</span>))</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>boot_stat_o3 <span class="ot">&lt;-</span> <span class="cf">function</span>(data, indices) {</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>  d <span class="ot">&lt;-</span> data[indices, ]</span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>  mean_la <span class="ot">&lt;-</span> <span class="fu">mean</span>(d<span class="sc">$</span>O3[d<span class="sc">$</span>City <span class="sc">==</span> <span class="st">"Los Angeles"</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>  mean_ny <span class="ot">&lt;-</span> <span class="fu">mean</span>(d<span class="sc">$</span>O3[d<span class="sc">$</span>City <span class="sc">==</span> <span class="st">"New York"</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a>  mean_la <span class="sc">-</span> mean_ny</span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a>boot_res_o3 <span class="ot">&lt;-</span> <span class="fu">boot</span>(<span class="at">data =</span> la_ny_o3,</span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a>                    <span class="at">statistic =</span> boot_stat_o3,</span>
<span id="cb74-12"><a href="#cb74-12" aria-hidden="true" tabindex="-1"></a>                    <span class="at">R =</span> <span class="dv">2000</span>)</span>
<span id="cb74-13"><a href="#cb74-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-14"><a href="#cb74-14" aria-hidden="true" tabindex="-1"></a>boot_res_o3</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
ORDINARY NONPARAMETRIC BOOTSTRAP


Call:
boot(data = la_ny_o3, statistic = boot_stat_o3, R = 2000)


Bootstrap Statistics :
       original       bias    std. error
t1* 0.002024126 1.160511e-05 0.000769248</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boot.ci</span>(boot_res_o3, <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"perc"</span>, <span class="st">"bca"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>BOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS
Based on 2000 bootstrap replicates

CALL : 
boot.ci(boot.out = boot_res_o3, type = c("perc", "bca"))

Intervals : 
Level     Percentile            BCa          
95%   ( 0.0005,  0.0036 )   ( 0.0005,  0.0036 )  
Calculations and Intervals on Original Scale</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>chi_hou_no2 <span class="ot">&lt;-</span> air_df_clean <span class="sc">%&gt;%</span> </span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(City <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Chicago"</span>, <span class="st">"Houston"</span>))</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(NO2 <span class="sc">~</span> City, <span class="at">data =</span> chi_hou_no2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  NO2 by City
W = 20024, p-value = 1.202e-05
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>boot_stat_no2 <span class="ot">&lt;-</span> <span class="cf">function</span>(data, indices) {</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>  d <span class="ot">&lt;-</span> data[indices, ]</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>  mean_chicago <span class="ot">&lt;-</span> <span class="fu">mean</span>(d<span class="sc">$</span>NO2[d<span class="sc">$</span>City <span class="sc">==</span> <span class="st">"Chicago"</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>  mean_houston <span class="ot">&lt;-</span> <span class="fu">mean</span>(d<span class="sc">$</span>NO2[d<span class="sc">$</span>City <span class="sc">==</span> <span class="st">"Houston"</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>  mean_chicago <span class="sc">-</span> mean_houston</span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a>boot_res_no2 <span class="ot">&lt;-</span> <span class="fu">boot</span>(<span class="at">data =</span> chi_hou_no2,</span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a>                     <span class="at">statistic =</span> boot_stat_no2,</span>
<span id="cb80-11"><a href="#cb80-11" aria-hidden="true" tabindex="-1"></a>                     <span class="at">R =</span> <span class="dv">2000</span>)</span>
<span id="cb80-12"><a href="#cb80-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-13"><a href="#cb80-13" aria-hidden="true" tabindex="-1"></a>boot_res_no2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
ORDINARY NONPARAMETRIC BOOTSTRAP


Call:
boot(data = chi_hou_no2, statistic = boot_stat_no2, R = 2000)


Bootstrap Statistics :
    original      bias    std. error
t1* 2.580291 -0.01103265   0.6313112</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boot.ci</span>(boot_res_no2, <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"perc"</span>, <span class="st">"bca"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>BOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS
Based on 2000 bootstrap replicates

CALL : 
boot.ci(boot.out = boot_res_no2, type = c("perc", "bca"))

Intervals : 
Level     Percentile            BCa          
95%   ( 1.364,  3.867 )   ( 1.451,  3.947 )  
Calculations and Intervals on Original Scale</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><br>
To quantify differences in nitrogen dioxide (NO₂) exposure between Chicago and Houston, we conducted a nonparametric bootstrap with 2,000 resamples. The observed difference in mean NO₂ was 2.58 ppb, with Chicago exhibiting higher levels.</p>
<p>The 95% percentile bootstrap interval (1.36, 3.87) and the BCa interval (1.45, 3.95) both excluded zero, indicating strong statistical evidence that Chicago’s mean NO₂ concentration is higher than Houston’s.</p>
<p>This difference is not only statistically significant but also meaningful in a public-health context. NO₂ differences of 2–4 ppb have been associated with increased risks of asthma exacerbations, respiratory stress, and emergency department visits. The findings reflect underlying differences in traffic density, atmospheric conditions, and industrial structure between the two metropolitan areas.</p>
</blockquote>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>air_df_clean <span class="sc">%&gt;%</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(City <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Chicago"</span>, <span class="st">"Houston"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Month =</span> <span class="fu">month</span>(Date, <span class="at">label =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(City, Month) <span class="sc">%&gt;%</span></span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_NO2 =</span> <span class="fu">mean</span>(NO2, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Month, mean_NO2, <span class="at">group =</span> City, <span class="at">color =</span> City)) <span class="sc">+</span></span>
<span id="cb84-7"><a href="#cb84-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size =</span> <span class="fl">1.2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'City'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="air_pollutioni_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Warm air → more vertical mixing → pollution disperses<br>
</p>
<p>Cold air → less mixing → pollution stays trapped near surface</p>
<section id="lets-check-on-weekdays" class="level1">
<h1>lets check on weekdays</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>air_df_clean <span class="ot">&lt;-</span> air_df_clean <span class="sc">%&gt;%</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Weekday =</span> <span class="fu">wday</span>(Date, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">week_start =</span> <span class="dv">1</span>))</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>air_df_clean <span class="sc">%&gt;%</span></span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(City <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Chicago"</span>, <span class="st">"Houston"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(City, Weekday) <span class="sc">%&gt;%</span></span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_NO2 =</span> <span class="fu">mean</span>(NO2, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb87-7"><a href="#cb87-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Weekday, mean_NO2, <span class="at">color =</span> City, <span class="at">group =</span> City)) <span class="sc">+</span></span>
<span id="cb87-8"><a href="#cb87-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb87-9"><a href="#cb87-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Weekday vs Weekend NO₂ Levels"</span>, <span class="at">y =</span> <span class="st">"Mean NO₂ (ppb)"</span>) <span class="sc">+</span></span>
<span id="cb87-10"><a href="#cb87-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">14</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'City'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="air_pollutioni_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>air_df_clean <span class="ot">&lt;-</span> air_df_clean <span class="sc">%&gt;%</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">day_type =</span> <span class="fu">ifelse</span>(Weekday <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Sat"</span>, <span class="st">"Sun"</span>), <span class="st">"Weekend"</span>, <span class="st">"Weekday"</span>)</span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>chi_week <span class="ot">&lt;-</span> air_df_clean <span class="sc">%&gt;%</span> <span class="fu">filter</span>(City <span class="sc">==</span> <span class="st">"Chicago"</span>)</span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(NO2 <span class="sc">~</span> day_type, <span class="at">data =</span> chi_week)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  NO2 by day_type
W = 870, p-value = 0.05645
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>hou_week <span class="ot">&lt;-</span> air_df_clean <span class="sc">%&gt;%</span> <span class="fu">filter</span>(City <span class="sc">==</span> <span class="st">"Houston"</span>)</span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(NO2 <span class="sc">~</span> day_type, <span class="at">data =</span> hou_week)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  NO2 by day_type
W = 17732, p-value = 7.717e-06
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>for Chicago, it is not statistically significant at 5 percent. For Houston, it is highly significant. houston shows strong weekday &gt; weekend NO2. So, NO2 rises with weekday commuting and falls on weekends. Traffic drives NO₂, but <em>meteorology (weather, winds, etc) determines how much</em> it shows up in air quality.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>pm25_matrix <span class="ot">&lt;-</span> air_df_clean <span class="sc">%&gt;%</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(City, Date, PM25) <span class="sc">%&gt;%</span></span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Date, <span class="at">values_from =</span> PM25) <span class="sc">%&gt;%</span></span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_to_rownames</span>(<span class="st">"City"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>o3_matrix <span class="ot">&lt;-</span> air_df_clean <span class="sc">%&gt;%</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(City, Date, O3) <span class="sc">%&gt;%</span></span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Date, <span class="at">values_from =</span> O3) <span class="sc">%&gt;%</span></span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_to_rownames</span>(<span class="st">"City"</span>)</span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a>no2_matrix <span class="ot">&lt;-</span> air_df_clean <span class="sc">%&gt;%</span></span>
<span id="cb94-7"><a href="#cb94-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(City, Date, NO2) <span class="sc">%&gt;%</span></span>
<span id="cb94-8"><a href="#cb94-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Date, <span class="at">values_from =</span> NO2) <span class="sc">%&gt;%</span></span>
<span id="cb94-9"><a href="#cb94-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_to_rownames</span>(<span class="st">"City"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>ts_matrix <span class="ot">&lt;-</span> <span class="fu">cbind</span>(pm25_matrix, o3_matrix, no2_matrix)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>ts_scaled <span class="ot">&lt;-</span> <span class="fu">scale</span>(ts_matrix)</span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(ts_matrix))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>2023-03-01 2023-03-02 2023-03-04 2023-03-07 2023-03-10 2023-03-13 2023-03-16 
         0          0          0          0          0          0          0 
2023-03-19 2023-03-22 2023-03-24 2023-03-25 2023-03-28 2023-03-31 2023-04-03 
         0          0          0          0          0          0          0 
2023-04-04 2023-04-06 2023-04-09 2023-04-12 2023-04-15 2023-04-18 2023-04-20 
         0          0          0          0          0          0          0 
2023-04-21 2023-04-24 2023-04-27 2023-04-30 2023-05-03 2023-05-06 2023-05-07 
         0          0          0          0          0          0          0 
2023-05-09 2023-05-12 2023-05-15 2023-05-18 2023-05-21 2023-05-24 2023-05-27 
         0          0          0          0          0          0          0 
2023-05-30 2023-06-02 2023-06-05 2023-06-08 2023-06-11 2023-06-14 2023-06-17 
         0          0          0          0          0          0          0 
2023-06-20 2023-06-23 2023-06-26 2023-06-29 2023-07-11 2023-07-14 2023-07-17 
         0          0          0          0          0          0          0 
2023-07-20 2023-07-23 2023-07-26 2023-07-29 2023-08-01 2023-08-04 2023-08-07 
         0          0          0          0          0          0          0 
2023-08-10 2023-08-13 2023-08-16 2023-08-19 2023-08-22 2023-08-25 2023-08-28 
         0          0          0          0          0          0          0 
2023-08-31 2023-09-03 2023-09-06 2023-09-09 2023-09-12 2023-09-15 2023-09-18 
         0          0          0          0          0          0          0 
2023-09-21 2023-09-24 2023-09-27 2023-09-30 2023-10-03 2023-10-06 2023-10-09 
         0          0          0          0          0          0          0 
2023-10-12 2023-10-15 2023-10-18 2023-10-21 2023-10-24 2023-10-27 2023-10-30 
         0          0          0          0          0          0          0 
2023-01-01 2023-01-02 2023-01-03 2023-01-04 2023-01-05 2023-01-06 2023-01-07 
         1          1          1          1          1          1          1 
2023-01-08 2023-01-09 2023-01-10 2023-01-11 2023-01-12 2023-01-13 2023-01-14 
         1          1          1          1          1          1          1 
2023-01-15 2023-01-16 2023-01-17 2023-01-18 2023-01-19 2023-01-20 2023-01-21 
         1          1          1          1          1          1          1 
2023-01-22 2023-01-23 2023-01-24 2023-01-25 2023-01-26 2023-01-27 2023-01-28 
         1          1          1          1          1          1          1 
2023-01-29 2023-01-30 2023-01-31 2023-02-01 2023-02-02 2023-02-03 2023-02-04 
         1          1          1          1          1          1          1 
2023-02-05 2023-02-06 2023-02-07 2023-02-08 2023-02-09 2023-02-10 2023-02-11 
         1          1          1          1          1          1          1 
2023-02-12 2023-02-13 2023-02-14 2023-02-15 2023-02-16 2023-02-17 2023-02-18 
         1          1          1          1          1          1          1 
2023-02-19 2023-02-20 2023-02-21 2023-02-22 2023-02-23 2023-02-24 2023-02-25 
         1          1          1          1          1          1          1 
2023-02-26 2023-02-27 2023-02-28 2023-03-03 2023-03-05 2023-03-06 2023-03-08 
         1          1          1          1          1          1          1 
2023-03-09 2023-03-11 2023-03-12 2023-03-14 2023-03-15 2023-03-17 2023-03-18 
         1          1          1          1          1          1          1 
2023-03-20 2023-03-21 2023-03-23 2023-03-26 2023-03-27 2023-03-29 2023-03-30 
         1          1          1          1          1          1          1 
2023-04-01 2023-04-02 2023-04-05 2023-04-07 2023-04-08 2023-04-10 2023-04-11 
         1          1          1          1          1          1          1 
2023-04-13 2023-04-14 2023-04-16 2023-04-17 2023-04-19 2023-04-22 2023-04-23 
         1          1          1          1          1          1          1 
2023-04-25 2023-04-26 2023-04-28 2023-04-29 2023-05-01 2023-05-02 2023-05-04 
         1          1          1          1          1          1          1 
2023-05-05 2023-05-08 2023-05-10 2023-05-11 2023-05-13 2023-05-14 2023-05-16 
         1          1          1          1          1          1          1 
2023-05-17 2023-05-19 2023-05-20 2023-05-22 2023-05-23 2023-05-25 2023-05-26 
         1          1          1          1          1          1          1 
2023-05-28 2023-05-29 2023-05-31 2023-06-01 2023-06-03 2023-06-04 2023-06-06 
         1          1          1          1          1          1          1 
2023-06-07 2023-06-09 2023-06-10 2023-06-12 2023-06-13 2023-06-15 2023-06-16 
         1          1          1          1          1          1          1 
2023-06-18 2023-06-19 2023-06-21 2023-06-22 2023-06-24 2023-06-25 2023-06-27 
         1          1          1          1          1          1          1 
2023-06-28 2023-06-30 2023-07-01 2023-07-02 2023-07-03 2023-07-04 2023-07-05 
         1          1          1          1          1          1          1 
2023-07-06 2023-07-07 2023-07-08 2023-07-09 2023-07-10 2023-07-12 2023-07-13 
         1          1          1          1          1          1          1 
2023-07-15 2023-07-16 2023-07-18 2023-07-19 2023-07-21 2023-07-22 2023-07-24 
         2          1          1          1          1          1          1 
2023-07-25 2023-07-27 2023-07-28 2023-07-30 2023-07-31 2023-08-02 2023-08-03 
         1          1          1          1          1          1          1 
2023-08-05 2023-08-06 2023-08-08 2023-08-09 2023-08-11 2023-08-12 2023-08-14 
         1          1          1          1          1          1          1 
2023-08-15 2023-08-17 2023-08-18 2023-08-20 2023-08-21 2023-08-23 2023-08-24 
         1          1          1          1          1          1          1 
2023-08-26 2023-08-27 2023-08-29 2023-08-30 2023-09-01 2023-09-02 2023-09-04 
         1          1          1          1          1          1          1 
2023-09-05 2023-09-07 2023-09-08 2023-09-10 2023-09-11 2023-09-13 2023-09-14 
         1          1          1          1          1          1          1 
2023-09-16 2023-09-17 2023-09-19 2023-09-20 2023-09-22 2023-09-23 2023-09-25 
         1          1          1          1          1          1          1 
2023-09-26 2023-09-28 2023-09-29 2023-10-01 2023-10-02 2023-10-04 2023-10-05 
         1          1          1          1          1          1          1 
2023-10-07 2023-10-08 2023-10-10 2023-10-11 2023-10-13 2023-10-14 2023-10-16 
         1          1          1          1          1          1          1 
2023-10-17 2023-10-19 2023-10-20 2023-10-22 2023-10-23 2023-10-25 2023-10-26 
         1          1          1          1          1          1          1 
2023-10-28 2023-10-29 2023-10-31 2023-11-01 2023-11-02 2023-11-03 2023-11-04 
         1          1          1          1          1          1          1 
2023-11-05 2023-11-06 2023-11-07 2023-11-08 2023-11-09 2023-11-10 2023-11-11 
         1          2          1          1          1          1          1 
2023-11-12 2023-11-13 2023-11-14 2023-11-15 2023-11-16 2023-11-17 2023-11-18 
         1          1          1          1          1          1          1 
2023-11-19 2023-11-20 2023-11-21 2023-11-22 2023-11-23 2023-11-24 2023-11-25 
         1          1          1          1          1          1          1 
2023-11-26 2023-11-27 2023-11-28 2023-11-29 2023-11-30 2023-12-01 2023-12-02 
         1          1          1          1          1          1          1 
2023-12-03 2023-12-04 2023-12-05 2023-12-06 2023-12-07 2023-12-08 2023-12-09 
         1          1          1          1          1          1          1 
2023-12-10 2023-12-11 2023-12-12 2023-12-13 2023-12-14 2023-12-15 2023-12-16 
         1          1          1          1          1          1          1 
2023-12-17 2023-12-18 2023-12-19 2023-12-20 2023-12-21 2023-12-22 2023-12-23 
         1          1          1          1          1          1          1 
2023-12-24 2023-12-25 2023-12-26 2023-12-27 2023-12-28 2023-12-29 2023-12-30 
         1          1          1          1          1          1          1 
2023-12-31 2023-03-01 2023-03-02 2023-03-04 2023-03-07 2023-03-10 2023-03-13 
         1          0          0          0          0          0          0 
2023-03-16 2023-03-19 2023-03-22 2023-03-24 2023-03-25 2023-03-28 2023-03-31 
         0          0          0          0          0          0          0 
2023-04-03 2023-04-04 2023-04-06 2023-04-09 2023-04-12 2023-04-15 2023-04-18 
         0          0          0          0          0          0          0 
2023-04-20 2023-04-21 2023-04-24 2023-04-27 2023-04-30 2023-05-03 2023-05-06 
         0          0          0          0          0          0          0 
2023-05-07 2023-05-09 2023-05-12 2023-05-15 2023-05-18 2023-05-21 2023-05-24 
         0          0          0          0          0          0          0 
2023-05-27 2023-05-30 2023-06-02 2023-06-05 2023-06-08 2023-06-11 2023-06-14 
         0          0          0          0          0          0          0 
2023-06-17 2023-06-20 2023-06-23 2023-06-26 2023-06-29 2023-07-11 2023-07-14 
         0          0          0          0          0          0          0 
2023-07-17 2023-07-20 2023-07-23 2023-07-26 2023-07-29 2023-08-01 2023-08-04 
         0          0          0          0          0          0          0 
2023-08-07 2023-08-10 2023-08-13 2023-08-16 2023-08-19 2023-08-22 2023-08-25 
         0          0          0          0          0          0          0 
2023-08-28 2023-08-31 2023-09-03 2023-09-06 2023-09-09 2023-09-12 2023-09-15 
         0          0          0          0          0          0          0 
2023-09-18 2023-09-21 2023-09-24 2023-09-27 2023-09-30 2023-10-03 2023-10-06 
         0          0          0          0          0          0          0 
2023-10-09 2023-10-12 2023-10-15 2023-10-18 2023-10-21 2023-10-24 2023-10-27 
         0          0          0          0          0          0          0 
2023-10-30 2023-01-01 2023-01-02 2023-01-03 2023-01-04 2023-01-05 2023-01-06 
         0          1          1          1          1          1          1 
2023-01-07 2023-01-08 2023-01-09 2023-01-10 2023-01-11 2023-01-12 2023-01-13 
         1          1          1          1          1          1          1 
2023-01-14 2023-01-15 2023-01-16 2023-01-17 2023-01-18 2023-01-19 2023-01-20 
         1          1          1          1          1          1          1 
2023-01-21 2023-01-22 2023-01-23 2023-01-24 2023-01-25 2023-01-26 2023-01-27 
         1          1          1          1          1          1          1 
2023-01-28 2023-01-29 2023-01-30 2023-01-31 2023-02-01 2023-02-02 2023-02-03 
         1          1          1          1          1          1          1 
2023-02-04 2023-02-05 2023-02-06 2023-02-07 2023-02-08 2023-02-09 2023-02-10 
         1          1          1          1          1          1          1 
2023-02-11 2023-02-12 2023-02-13 2023-02-14 2023-02-15 2023-02-16 2023-02-17 
         1          1          1          1          1          1          1 
2023-02-18 2023-02-19 2023-02-20 2023-02-21 2023-02-22 2023-02-23 2023-02-24 
         1          1          1          1          1          1          1 
2023-02-25 2023-02-26 2023-02-27 2023-02-28 2023-03-03 2023-03-05 2023-03-06 
         1          1          1          1          1          1          1 
2023-03-08 2023-03-09 2023-03-11 2023-03-12 2023-03-14 2023-03-15 2023-03-17 
         1          1          1          1          1          1          1 
2023-03-18 2023-03-20 2023-03-21 2023-03-23 2023-03-26 2023-03-27 2023-03-29 
         1          1          1          1          1          1          1 
2023-03-30 2023-04-01 2023-04-02 2023-04-05 2023-04-07 2023-04-08 2023-04-10 
         1          1          1          1          1          1          1 
2023-04-11 2023-04-13 2023-04-14 2023-04-16 2023-04-17 2023-04-19 2023-04-22 
         1          1          1          1          1          1          1 
2023-04-23 2023-04-25 2023-04-26 2023-04-28 2023-04-29 2023-05-01 2023-05-02 
         1          1          1          1          1          1          1 
2023-05-04 2023-05-05 2023-05-08 2023-05-10 2023-05-11 2023-05-13 2023-05-14 
         1          1          1          1          1          1          1 
2023-05-16 2023-05-17 2023-05-19 2023-05-20 2023-05-22 2023-05-23 2023-05-25 
         1          1          1          1          1          1          1 
2023-05-26 2023-05-28 2023-05-29 2023-05-31 2023-06-01 2023-06-03 2023-06-04 
         1          1          1          1          1          1          1 
2023-06-06 2023-06-07 2023-06-09 2023-06-10 2023-06-12 2023-06-13 2023-06-15 
         1          1          1          1          1          1          1 
2023-06-16 2023-06-18 2023-06-19 2023-06-21 2023-06-22 2023-06-24 2023-06-25 
         1          1          1          1          1          1          1 
2023-06-27 2023-06-28 2023-06-30 2023-07-01 2023-07-02 2023-07-03 2023-07-04 
         1          1          1          1          1          1          1 
2023-07-05 2023-07-06 2023-07-07 2023-07-08 2023-07-09 2023-07-10 2023-07-12 
         1          1          1          1          1          1          1 
2023-07-13 2023-07-15 2023-07-16 2023-07-18 2023-07-19 2023-07-21 2023-07-22 
         1          2          1          1          1          1          1 
2023-07-24 2023-07-25 2023-07-27 2023-07-28 2023-07-30 2023-07-31 2023-08-02 
         1          1          1          1          1          1          1 
2023-08-03 2023-08-05 2023-08-06 2023-08-08 2023-08-09 2023-08-11 2023-08-12 
         1          1          1          1          1          1          1 
2023-08-14 2023-08-15 2023-08-17 2023-08-18 2023-08-20 2023-08-21 2023-08-23 
         1          1          1          1          1          1          1 
2023-08-24 2023-08-26 2023-08-27 2023-08-29 2023-08-30 2023-09-01 2023-09-02 
         1          1          1          1          1          1          1 
2023-09-04 2023-09-05 2023-09-07 2023-09-08 2023-09-10 2023-09-11 2023-09-13 
         1          1          1          1          1          1          1 
2023-09-14 2023-09-16 2023-09-17 2023-09-19 2023-09-20 2023-09-22 2023-09-23 
         1          1          1          1          1          1          1 
2023-09-25 2023-09-26 2023-09-28 2023-09-29 2023-10-01 2023-10-02 2023-10-04 
         1          1          1          1          1          1          1 
2023-10-05 2023-10-07 2023-10-08 2023-10-10 2023-10-11 2023-10-13 2023-10-14 
         1          1          1          1          1          1          1 
2023-10-16 2023-10-17 2023-10-19 2023-10-20 2023-10-22 2023-10-23 2023-10-25 
         1          1          1          1          1          1          1 
2023-10-26 2023-10-28 2023-10-29 2023-10-31 2023-11-01 2023-11-02 2023-11-03 
         1          1          1          1          1          1          1 
2023-11-04 2023-11-05 2023-11-06 2023-11-07 2023-11-08 2023-11-09 2023-11-10 
         1          1          2          1          1          1          1 
2023-11-11 2023-11-12 2023-11-13 2023-11-14 2023-11-15 2023-11-16 2023-11-17 
         1          1          1          1          1          1          1 
2023-11-18 2023-11-19 2023-11-20 2023-11-21 2023-11-22 2023-11-23 2023-11-24 
         1          1          1          1          1          1          1 
2023-11-25 2023-11-26 2023-11-27 2023-11-28 2023-11-29 2023-11-30 2023-12-01 
         1          1          1          1          1          1          1 
2023-12-02 2023-12-03 2023-12-04 2023-12-05 2023-12-06 2023-12-07 2023-12-08 
         1          1          1          1          1          1          1 
2023-12-09 2023-12-10 2023-12-11 2023-12-12 2023-12-13 2023-12-14 2023-12-15 
         1          1          1          1          1          1          1 
2023-12-16 2023-12-17 2023-12-18 2023-12-19 2023-12-20 2023-12-21 2023-12-22 
         1          1          1          1          1          1          1 
2023-12-23 2023-12-24 2023-12-25 2023-12-26 2023-12-27 2023-12-28 2023-12-29 
         1          1          1          1          1          1          1 
2023-12-30 2023-12-31 2023-03-01 2023-03-02 2023-03-04 2023-03-07 2023-03-10 
         1          1          0          0          0          0          0 
2023-03-13 2023-03-16 2023-03-19 2023-03-22 2023-03-24 2023-03-25 2023-03-28 
         0          0          0          0          0          0          0 
2023-03-31 2023-04-03 2023-04-04 2023-04-06 2023-04-09 2023-04-12 2023-04-15 
         0          0          0          0          0          0          0 
2023-04-18 2023-04-20 2023-04-21 2023-04-24 2023-04-27 2023-04-30 2023-05-03 
         0          0          0          0          0          0          0 
2023-05-06 2023-05-07 2023-05-09 2023-05-12 2023-05-15 2023-05-18 2023-05-21 
         0          0          0          0          0          0          0 
2023-05-24 2023-05-27 2023-05-30 2023-06-02 2023-06-05 2023-06-08 2023-06-11 
         0          0          0          0          0          0          0 
2023-06-14 2023-06-17 2023-06-20 2023-06-23 2023-06-26 2023-06-29 2023-07-11 
         0          0          0          0          0          0          0 
2023-07-14 2023-07-17 2023-07-20 2023-07-23 2023-07-26 2023-07-29 2023-08-01 
         0          0          0          0          0          0          0 
2023-08-04 2023-08-07 2023-08-10 2023-08-13 2023-08-16 2023-08-19 2023-08-22 
         0          0          0          0          0          0          0 
2023-08-25 2023-08-28 2023-08-31 2023-09-03 2023-09-06 2023-09-09 2023-09-12 
         0          0          0          0          0          0          0 
2023-09-15 2023-09-18 2023-09-21 2023-09-24 2023-09-27 2023-09-30 2023-10-03 
         0          0          0          0          0          0          0 
2023-10-06 2023-10-09 2023-10-12 2023-10-15 2023-10-18 2023-10-21 2023-10-24 
         0          0          0          0          0          0          0 
2023-10-27 2023-10-30 2023-01-01 2023-01-02 2023-01-03 2023-01-04 2023-01-05 
         0          0          1          1          1          1          1 
2023-01-06 2023-01-07 2023-01-08 2023-01-09 2023-01-10 2023-01-11 2023-01-12 
         1          1          1          1          1          1          1 
2023-01-13 2023-01-14 2023-01-15 2023-01-16 2023-01-17 2023-01-18 2023-01-19 
         1          1          1          1          1          1          1 
2023-01-20 2023-01-21 2023-01-22 2023-01-23 2023-01-24 2023-01-25 2023-01-26 
         1          1          1          1          1          1          1 
2023-01-27 2023-01-28 2023-01-29 2023-01-30 2023-01-31 2023-02-01 2023-02-02 
         1          1          1          1          1          1          1 
2023-02-03 2023-02-04 2023-02-05 2023-02-06 2023-02-07 2023-02-08 2023-02-09 
         1          1          1          1          1          1          1 
2023-02-10 2023-02-11 2023-02-12 2023-02-13 2023-02-14 2023-02-15 2023-02-16 
         1          1          1          1          1          1          1 
2023-02-17 2023-02-18 2023-02-19 2023-02-20 2023-02-21 2023-02-22 2023-02-23 
         1          1          1          1          1          1          1 
2023-02-24 2023-02-25 2023-02-26 2023-02-27 2023-02-28 2023-03-03 2023-03-05 
         1          1          1          1          1          1          1 
2023-03-06 2023-03-08 2023-03-09 2023-03-11 2023-03-12 2023-03-14 2023-03-15 
         1          1          1          1          1          1          1 
2023-03-17 2023-03-18 2023-03-20 2023-03-21 2023-03-23 2023-03-26 2023-03-27 
         1          1          1          1          1          1          1 
2023-03-29 2023-03-30 2023-04-01 2023-04-02 2023-04-05 2023-04-07 2023-04-08 
         1          1          1          1          1          1          1 
2023-04-10 2023-04-11 2023-04-13 2023-04-14 2023-04-16 2023-04-17 2023-04-19 
         1          1          1          1          1          1          1 
2023-04-22 2023-04-23 2023-04-25 2023-04-26 2023-04-28 2023-04-29 2023-05-01 
         1          1          1          1          1          1          1 
2023-05-02 2023-05-04 2023-05-05 2023-05-08 2023-05-10 2023-05-11 2023-05-13 
         1          1          1          1          1          1          1 
2023-05-14 2023-05-16 2023-05-17 2023-05-19 2023-05-20 2023-05-22 2023-05-23 
         1          1          1          1          1          1          1 
2023-05-25 2023-05-26 2023-05-28 2023-05-29 2023-05-31 2023-06-01 2023-06-03 
         1          1          1          1          1          1          1 
2023-06-04 2023-06-06 2023-06-07 2023-06-09 2023-06-10 2023-06-12 2023-06-13 
         1          1          1          1          1          1          1 
2023-06-15 2023-06-16 2023-06-18 2023-06-19 2023-06-21 2023-06-22 2023-06-24 
         1          1          1          1          1          1          1 
2023-06-25 2023-06-27 2023-06-28 2023-06-30 2023-07-01 2023-07-02 2023-07-03 
         1          1          1          1          1          1          1 
2023-07-04 2023-07-05 2023-07-06 2023-07-07 2023-07-08 2023-07-09 2023-07-10 
         1          1          1          1          1          1          1 
2023-07-12 2023-07-13 2023-07-15 2023-07-16 2023-07-18 2023-07-19 2023-07-21 
         1          1          2          1          1          1          1 
2023-07-22 2023-07-24 2023-07-25 2023-07-27 2023-07-28 2023-07-30 2023-07-31 
         1          1          1          1          1          1          1 
2023-08-02 2023-08-03 2023-08-05 2023-08-06 2023-08-08 2023-08-09 2023-08-11 
         1          1          1          1          1          1          1 
2023-08-12 2023-08-14 2023-08-15 2023-08-17 2023-08-18 2023-08-20 2023-08-21 
         1          1          1          1          1          1          1 
2023-08-23 2023-08-24 2023-08-26 2023-08-27 2023-08-29 2023-08-30 2023-09-01 
         1          1          1          1          1          1          1 
2023-09-02 2023-09-04 2023-09-05 2023-09-07 2023-09-08 2023-09-10 2023-09-11 
         1          1          1          1          1          1          1 
2023-09-13 2023-09-14 2023-09-16 2023-09-17 2023-09-19 2023-09-20 2023-09-22 
         1          1          1          1          1          1          1 
2023-09-23 2023-09-25 2023-09-26 2023-09-28 2023-09-29 2023-10-01 2023-10-02 
         1          1          1          1          1          1          1 
2023-10-04 2023-10-05 2023-10-07 2023-10-08 2023-10-10 2023-10-11 2023-10-13 
         1          1          1          1          1          1          1 
2023-10-14 2023-10-16 2023-10-17 2023-10-19 2023-10-20 2023-10-22 2023-10-23 
         1          1          1          1          1          1          1 
2023-10-25 2023-10-26 2023-10-28 2023-10-29 2023-10-31 2023-11-01 2023-11-02 
         1          1          1          1          1          1          1 
2023-11-03 2023-11-04 2023-11-05 2023-11-06 2023-11-07 2023-11-08 2023-11-09 
         1          1          1          2          1          1          1 
2023-11-10 2023-11-11 2023-11-12 2023-11-13 2023-11-14 2023-11-15 2023-11-16 
         1          1          1          1          1          1          1 
2023-11-17 2023-11-18 2023-11-19 2023-11-20 2023-11-21 2023-11-22 2023-11-23 
         1          1          1          1          1          1          1 
2023-11-24 2023-11-25 2023-11-26 2023-11-27 2023-11-28 2023-11-29 2023-11-30 
         1          1          1          1          1          1          1 
2023-12-01 2023-12-02 2023-12-03 2023-12-04 2023-12-05 2023-12-06 2023-12-07 
         1          1          1          1          1          1          1 
2023-12-08 2023-12-09 2023-12-10 2023-12-11 2023-12-12 2023-12-13 2023-12-14 
         1          1          1          1          1          1          1 
2023-12-15 2023-12-16 2023-12-17 2023-12-18 2023-12-19 2023-12-20 2023-12-21 
         1          1          1          1          1          1          1 
2023-12-22 2023-12-23 2023-12-24 2023-12-25 2023-12-26 2023-12-27 2023-12-28 
         1          1          1          1          1          1          1 
2023-12-29 2023-12-30 2023-12-31 
         1          1          1 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a><span class="co"># km3 &lt;- kmeans(ts_scaled, centers = 3, nstart = 25)</span></span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a><span class="co"># km3$cluster</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>ran into an issue of many NAs and k-means doesn’t work well with null values, so we are going to replace the na values with the mean.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(zoo)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'zoo'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    as.Date, as.Date.numeric</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>ts_matrix_imputed <span class="ot">&lt;-</span> ts_matrix <span class="sc">%&gt;%</span> </span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">apply</span>(<span class="dv">1</span>, <span class="cf">function</span>(row) <span class="fu">na.approx</span>(row, <span class="at">na.rm =</span> <span class="cn">FALSE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">t</span>()</span>
<span id="cb102-4"><a href="#cb102-4" aria-hidden="true" tabindex="-1"></a>ts_matrix_imputed <span class="ot">&lt;-</span> <span class="fu">apply</span>(ts_matrix_imputed, <span class="dv">1</span>, <span class="cf">function</span>(row){</span>
<span id="cb102-5"><a href="#cb102-5" aria-hidden="true" tabindex="-1"></a>  row[<span class="fu">is.na</span>(row)] <span class="ot">&lt;-</span> <span class="fu">mean</span>(row, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb102-6"><a href="#cb102-6" aria-hidden="true" tabindex="-1"></a>  row</span>
<span id="cb102-7"><a href="#cb102-7" aria-hidden="true" tabindex="-1"></a>}) <span class="sc">%&gt;%</span> <span class="fu">t</span>()</span>
<span id="cb102-8"><a href="#cb102-8" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(ts_matrix_imputed))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>scaling the matrix again:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>ts_scaled <span class="ot">&lt;-</span> <span class="fu">scale</span>(ts_matrix_imputed)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>km3 <span class="ot">&lt;-</span> <span class="fu">kmeans</span>(ts_scaled, <span class="at">centers =</span> <span class="dv">3</span>, <span class="at">nstart =</span> <span class="dv">25</span>)</span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a>km3<span class="sc">$</span>cluster</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Chicago       Dallas      Houston  Los Angeles     New York Philadelphia 
           1            3            3            2            2            2 
     Phoenix  San Antonio    San Diego     San Jose 
           2            3            2            2 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(factoextra)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Welcome! Want to learn more? See two factoextra-related books at https://goo.gl/ve3WBa</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_cluster</span>(km3, <span class="at">data =</span> ts_scaled, <span class="at">geom =</span> <span class="st">"point"</span>, <span class="at">repel =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="air_pollutioni_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>test i need to do before ARIMA modelling:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tseries::adf.test(ts_series)</span></span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ndiffs(ts_series)</span></span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a><span class="co"># nsdiffs(ts_series)</span></span>
<span id="cb110-4"><a href="#cb110-4" aria-hidden="true" tabindex="-1"></a><span class="co"># checkresiduals(fit)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forecast)</span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb111-4"><a href="#cb111-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-5"><a href="#cb111-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Cities</span></span>
<span id="cb111-6"><a href="#cb111-6" aria-hidden="true" tabindex="-1"></a>cities <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb111-7"><a href="#cb111-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"New York"</span>, <span class="st">"Los Angeles"</span>, <span class="st">"Chicago"</span>, <span class="st">"Houston"</span>, <span class="st">"Phoenix"</span>,</span>
<span id="cb111-8"><a href="#cb111-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Philadelphia"</span>, <span class="st">"San Antonio"</span>, <span class="st">"San Diego"</span>, <span class="st">"Dallas"</span>, <span class="st">"San Jose"</span></span>
<span id="cb111-9"><a href="#cb111-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb111-10"><a href="#cb111-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-11"><a href="#cb111-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Pollutants</span></span>
<span id="cb111-12"><a href="#cb111-12" aria-hidden="true" tabindex="-1"></a>pollutants <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"PM25"</span>, <span class="st">"O3"</span>, <span class="st">"NO2"</span>)</span>
<span id="cb111-13"><a href="#cb111-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-14"><a href="#cb111-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Storage lists</span></span>
<span id="cb111-15"><a href="#cb111-15" aria-hidden="true" tabindex="-1"></a>arima_models <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb111-16"><a href="#cb111-16" aria-hidden="true" tabindex="-1"></a>arima_diagnostics <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb111-17"><a href="#cb111-17" aria-hidden="true" tabindex="-1"></a>arima_forecasts <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb111-18"><a href="#cb111-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-19"><a href="#cb111-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Loop through each city and pollutant</span></span>
<span id="cb111-20"><a href="#cb111-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (city <span class="cf">in</span> cities) {</span>
<span id="cb111-21"><a href="#cb111-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">===========================</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb111-22"><a href="#cb111-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"CITY:"</span>, city, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb111-23"><a href="#cb111-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"===========================</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb111-24"><a href="#cb111-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-25"><a href="#cb111-25" aria-hidden="true" tabindex="-1"></a>  city_df <span class="ot">&lt;-</span> air_df_clean <span class="sc">%&gt;%</span> </span>
<span id="cb111-26"><a href="#cb111-26" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(City <span class="sc">==</span> city) <span class="sc">%&gt;%</span> </span>
<span id="cb111-27"><a href="#cb111-27" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(Date)</span>
<span id="cb111-28"><a href="#cb111-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-29"><a href="#cb111-29" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (poll <span class="cf">in</span> pollutants) {</span>
<span id="cb111-30"><a href="#cb111-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-31"><a href="#cb111-31" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"---- Pollutant:"</span>, poll, <span class="st">"----</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb111-32"><a href="#cb111-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-33"><a href="#cb111-33" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Extract time series</span></span>
<span id="cb111-34"><a href="#cb111-34" aria-hidden="true" tabindex="-1"></a>    ts_data <span class="ot">&lt;-</span> city_df[[poll]]</span>
<span id="cb111-35"><a href="#cb111-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-36"><a href="#cb111-36" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Convert to a daily ts object</span></span>
<span id="cb111-37"><a href="#cb111-37" aria-hidden="true" tabindex="-1"></a>    ts_series <span class="ot">&lt;-</span> <span class="fu">ts</span>(ts_data, <span class="at">frequency =</span> <span class="dv">365</span>)</span>
<span id="cb111-38"><a href="#cb111-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-39"><a href="#cb111-39" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Fit ARIMA model</span></span>
<span id="cb111-40"><a href="#cb111-40" aria-hidden="true" tabindex="-1"></a>    fit <span class="ot">&lt;-</span> <span class="fu">auto.arima</span>(ts_series, <span class="at">seasonal =</span> <span class="cn">TRUE</span>, <span class="at">stepwise =</span> <span class="cn">FALSE</span>, <span class="at">approximation =</span> <span class="cn">FALSE</span>)</span>
<span id="cb111-41"><a href="#cb111-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-42"><a href="#cb111-42" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Save model</span></span>
<span id="cb111-43"><a href="#cb111-43" aria-hidden="true" tabindex="-1"></a>    arima_models[[<span class="fu">paste</span>(city, poll, <span class="at">sep =</span> <span class="st">"_"</span>)]] <span class="ot">&lt;-</span> fit</span>
<span id="cb111-44"><a href="#cb111-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-45"><a href="#cb111-45" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Diagnostics</span></span>
<span id="cb111-46"><a href="#cb111-46" aria-hidden="true" tabindex="-1"></a>    diag <span class="ot">&lt;-</span> <span class="fu">checkresiduals</span>(fit, <span class="at">plot =</span> <span class="cn">FALSE</span>)</span>
<span id="cb111-47"><a href="#cb111-47" aria-hidden="true" tabindex="-1"></a>    arima_diagnostics[[<span class="fu">paste</span>(city, poll, <span class="at">sep =</span> <span class="st">"_"</span>)]] <span class="ot">&lt;-</span> diag</span>
<span id="cb111-48"><a href="#cb111-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-49"><a href="#cb111-49" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Forecast 30 days ahead</span></span>
<span id="cb111-50"><a href="#cb111-50" aria-hidden="true" tabindex="-1"></a>    fcast <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit, <span class="at">h =</span> <span class="dv">30</span>)</span>
<span id="cb111-51"><a href="#cb111-51" aria-hidden="true" tabindex="-1"></a>    arima_forecasts[[<span class="fu">paste</span>(city, poll, <span class="at">sep =</span> <span class="st">"_"</span>)]] <span class="ot">&lt;-</span> fcast</span>
<span id="cb111-52"><a href="#cb111-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-53"><a href="#cb111-53" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Print important results</span></span>
<span id="cb111-54"><a href="#cb111-54" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"ARIMA Model:"</span>, fit<span class="sc">$</span>arma, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb111-55"><a href="#cb111-55" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"AIC:"</span>, fit<span class="sc">$</span>aic, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb111-56"><a href="#cb111-56" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"Residual Ljung-Box p-value:"</span>, diag<span class="sc">$</span>p.value, <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb111-57"><a href="#cb111-57" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb111-58"><a href="#cb111-58" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
===========================
CITY: New York 
===========================

---- Pollutant: PM25 ----

    Ljung-Box test

data:  Residuals from ARIMA(3,0,0) with non-zero mean
Q* = 39.041, df = 70, p-value = 0.999

Model df: 3.   Total lags used: 73

ARIMA Model: 3 0 0 0 365 0 0 
AIC: 2632.464 
Residual Ljung-Box p-value: 0.9989982 

---- Pollutant: O3 ----

    Ljung-Box test

data:  Residuals from ARIMA(0,1,5)
Q* = 100.41, df = 68, p-value = 0.006464

Model df: 5.   Total lags used: 73

ARIMA Model: 0 5 0 0 365 1 0 
AIC: -2515.042 
Residual Ljung-Box p-value: 0.006464271 

---- Pollutant: NO2 ----

    Ljung-Box test

data:  Residuals from ARIMA(1,1,3)
Q* = 152.5, df = 69, p-value = 3.032e-08

Model df: 4.   Total lags used: 73

ARIMA Model: 1 3 0 0 365 1 0 
AIC: 2314.934 
Residual Ljung-Box p-value: 3.032176e-08 


===========================
CITY: Los Angeles 
===========================

---- Pollutant: PM25 ----

    Ljung-Box test

data:  Residuals from ARIMA(1,1,2)
Q* = 73.251, df = 70, p-value = 0.3719

Model df: 3.   Total lags used: 73

ARIMA Model: 1 2 0 0 365 1 0 
AIC: 1904.193 
Residual Ljung-Box p-value: 0.3719123 

---- Pollutant: O3 ----

    Ljung-Box test

data:  Residuals from ARIMA(2,1,1)
Q* = 74.279, df = 70, p-value = 0.3407

Model df: 3.   Total lags used: 73

ARIMA Model: 2 1 0 0 365 1 0 
AIC: -2747.536 
Residual Ljung-Box p-value: 0.3406631 

---- Pollutant: NO2 ----

    Ljung-Box test

data:  Residuals from ARIMA(3,1,2)
Q* = 113.2, df = 68, p-value = 0.00048

Model df: 5.   Total lags used: 73

ARIMA Model: 3 2 0 0 365 1 0 
AIC: 2099.25 
Residual Ljung-Box p-value: 0.0004799913 


===========================
CITY: Chicago 
===========================

---- Pollutant: PM25 ----

    Ljung-Box test

data:  Residuals from ARIMA(1,0,1) with non-zero mean
Q* = 10.625, df = 15, p-value = 0.7787

Model df: 2.   Total lags used: 17

ARIMA Model: 1 1 0 0 365 0 0 
AIC: 554.1841 
Residual Ljung-Box p-value: 0.7787239 

---- Pollutant: O3 ----

    Ljung-Box test

data:  Residuals from ARIMA(0,1,2)
Q* = 14.023, df = 15, p-value = 0.5238

Model df: 2.   Total lags used: 17

ARIMA Model: 0 2 0 0 365 1 0 
AIC: -520.2603 
Residual Ljung-Box p-value: 0.5237644 

---- Pollutant: NO2 ----

    Ljung-Box test

data:  Residuals from ARIMA(1,0,0) with non-zero mean
Q* = 14.629, df = 16, p-value = 0.5519

Model df: 1.   Total lags used: 17

ARIMA Model: 1 0 0 0 365 0 0 
AIC: 514.2924 
Residual Ljung-Box p-value: 0.5519253 


===========================
CITY: Houston 
===========================

---- Pollutant: PM25 ----

    Ljung-Box test

data:  Residuals from ARIMA(1,1,1)
Q* = 57.317, df = 71, p-value = 0.8799

Model df: 2.   Total lags used: 73

ARIMA Model: 1 1 0 0 365 1 0 
AIC: 2009.294 
Residual Ljung-Box p-value: 0.8799387 

---- Pollutant: O3 ----

    Ljung-Box test

data:  Residuals from ARIMA(1,1,1)
Q* = 63.771, df = 71, p-value = 0.7164

Model df: 2.   Total lags used: 73

ARIMA Model: 1 1 0 0 365 1 0 
AIC: -2486.823 
Residual Ljung-Box p-value: 0.7163766 

---- Pollutant: NO2 ----

    Ljung-Box test

data:  Residuals from ARIMA(2,1,1)
Q* = 82.187, df = 70, p-value = 0.1512

Model df: 3.   Total lags used: 73

ARIMA Model: 2 1 0 0 365 1 0 
AIC: 1984.447 
Residual Ljung-Box p-value: 0.1512209 


===========================
CITY: Phoenix 
===========================

---- Pollutant: PM25 ----

    Ljung-Box test

data:  Residuals from ARIMA(5,1,0)
Q* = 63.587, df = 68, p-value = 0.6291

Model df: 5.   Total lags used: 73

ARIMA Model: 5 0 0 0 365 1 0 
AIC: 2038.357 
Residual Ljung-Box p-value: 0.6290588 

---- Pollutant: O3 ----

    Ljung-Box test

data:  Residuals from ARIMA(1,1,1)
Q* = 107.73, df = 71, p-value = 0.003228

Model df: 2.   Total lags used: 73

ARIMA Model: 1 1 0 0 365 1 0 
AIC: -2678.335 
Residual Ljung-Box p-value: 0.003228419 

---- Pollutant: NO2 ----

    Ljung-Box test

data:  Residuals from ARIMA(1,1,2)
Q* = 137.96, df = 70, p-value = 2.358e-06

Model df: 3.   Total lags used: 73

ARIMA Model: 1 2 0 0 365 1 0 
AIC: 2060.11 
Residual Ljung-Box p-value: 2.35763e-06 


===========================
CITY: Philadelphia 
===========================

---- Pollutant: PM25 ----

    Ljung-Box test

data:  Residuals from ARIMA(0,0,2) with non-zero mean
Q* = 47.144, df = 71, p-value = 0.987

Model df: 2.   Total lags used: 73

ARIMA Model: 0 2 0 0 365 0 0 
AIC: 2730.281 
Residual Ljung-Box p-value: 0.9870018 

---- Pollutant: O3 ----

    Ljung-Box test

data:  Residuals from ARIMA(2,1,2)
Q* = 86.574, df = 69, p-value = 0.07484

Model df: 4.   Total lags used: 73

ARIMA Model: 2 2 0 0 365 1 0 
AIC: -2557.532 
Residual Ljung-Box p-value: 0.07483531 

---- Pollutant: NO2 ----

    Ljung-Box test

data:  Residuals from ARIMA(4,1,1)
Q* = 154.26, df = 68, p-value = 1.198e-08

Model df: 5.   Total lags used: 73

ARIMA Model: 4 1 0 0 365 1 0 
AIC: 2118.003 
Residual Ljung-Box p-value: 1.198268e-08 


===========================
CITY: San Antonio 
===========================

---- Pollutant: PM25 ----

    Ljung-Box test

data:  Residuals from ARIMA(1,1,2)
Q* = 94.411, df = 70, p-value = 0.02758

Model df: 3.   Total lags used: 73

ARIMA Model: 1 2 0 0 365 1 0 
AIC: 2012.281 
Residual Ljung-Box p-value: 0.02758132 

---- Pollutant: O3 ----

    Ljung-Box test

data:  Residuals from ARIMA(1,1,1)
Q* = 64.674, df = 71, p-value = 0.6883

Model df: 2.   Total lags used: 73

ARIMA Model: 1 1 0 0 365 1 0 
AIC: -2602.408 
Residual Ljung-Box p-value: 0.6883079 

---- Pollutant: NO2 ----

    Ljung-Box test

data:  Residuals from ARIMA(1,1,2)
Q* = 57.815, df = 70, p-value = 0.8506

Model df: 3.   Total lags used: 73

ARIMA Model: 1 2 0 0 365 1 0 
AIC: 1529.822 
Residual Ljung-Box p-value: 0.8506436 


===========================
CITY: San Diego 
===========================

---- Pollutant: PM25 ----

    Ljung-Box test

data:  Residuals from ARIMA(2,1,1)
Q* = 59.637, df = 70, p-value = 0.8068

Model df: 3.   Total lags used: 73

ARIMA Model: 2 1 0 0 365 1 0 
AIC: 1737.816 
Residual Ljung-Box p-value: 0.8067955 

---- Pollutant: O3 ----

    Ljung-Box test

data:  Residuals from ARIMA(1,1,1)
Q* = 53.978, df = 71, p-value = 0.9338

Model df: 2.   Total lags used: 73

ARIMA Model: 1 1 0 0 365 1 0 
AIC: -2846.939 
Residual Ljung-Box p-value: 0.9337987 

---- Pollutant: NO2 ----

    Ljung-Box test

data:  Residuals from ARIMA(2,1,1)
Q* = 239.18, df = 70, p-value &lt; 2.2e-16

Model df: 3.   Total lags used: 73

ARIMA Model: 2 1 0 0 365 1 0 
AIC: 1866.703 
Residual Ljung-Box p-value: 0 


===========================
CITY: Dallas 
===========================

---- Pollutant: PM25 ----

    Ljung-Box test

data:  Residuals from ARIMA(1,0,1) with non-zero mean
Q* = 66.458, df = 71, p-value = 0.6305

Model df: 2.   Total lags used: 73

ARIMA Model: 1 1 0 0 365 0 0 
AIC: 2071.554 
Residual Ljung-Box p-value: 0.6305444 

---- Pollutant: O3 ----

    Ljung-Box test

data:  Residuals from ARIMA(1,1,1)
Q* = 52.557, df = 71, p-value = 0.9505

Model df: 2.   Total lags used: 73

ARIMA Model: 1 1 0 0 365 1 0 
AIC: -2510.533 
Residual Ljung-Box p-value: 0.9504586 

---- Pollutant: NO2 ----

    Ljung-Box test

data:  Residuals from ARIMA(0,1,3)
Q* = 60.905, df = 70, p-value = 0.7727

Model df: 3.   Total lags used: 73

ARIMA Model: 0 3 0 0 365 1 0 
AIC: 1946.622 
Residual Ljung-Box p-value: 0.7726873 


===========================
CITY: San Jose 
===========================

---- Pollutant: PM25 ----

    Ljung-Box test

data:  Residuals from ARIMA(2,1,1)
Q* = 37.857, df = 70, p-value = 0.9994

Model df: 3.   Total lags used: 73

ARIMA Model: 2 1 0 0 365 1 0 
AIC: 2006.258 
Residual Ljung-Box p-value: 0.9994028 

---- Pollutant: O3 ----

    Ljung-Box test

data:  Residuals from ARIMA(2,1,2)
Q* = 57.672, df = 69, p-value = 0.8328

Model df: 4.   Total lags used: 73

ARIMA Model: 2 2 0 0 365 1 0 
AIC: -2762.383 
Residual Ljung-Box p-value: 0.8327627 

---- Pollutant: NO2 ----

    Ljung-Box test

data:  Residuals from ARIMA(0,1,4)
Q* = 84.347, df = 69, p-value = 0.1009

Model df: 4.   Total lags used: 73

ARIMA Model: 0 4 0 0 365 1 0 
AIC: 1958.883 
Residual Ljung-Box p-value: 0.1009248 </code></pre>
</div>
</div>
<p>This test shows us that we failed many tests. failing Ljung-Box is extremely common in meterological and pollutant time series. this because the data has strong seasonality, periodic cycles (ARIMA can’t model weather shocks), long-memory behavior, non-linear patterns and calendar effects (weekday traffic/holiday). But what about the LJUNG tests above 0.05?</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>