---
title: "DSAN 5100 Group 5 Final Project"
format: html
---

# Libraries Used
```{r, message=FALSE}
library(tidyverse, verbose = FALSE)
library(lubridate, verbose = FALSE)
library(forecast, verbose = FALSE)
library(car, verbose = FALSE)
library(boot, verbose = FALSE)
library(zoo, verbose = FALSE)
library(factoextra, verbose = FALSE)
library(ggplot2, verbose = FALSE)
```

# Constants

```{r}
cities <- c(
  "New York", "Los Angeles", "Chicago", "Houston", "Phoenix",
  "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose"
)
set.seed(5100)
```

# Load Pollutant Data
```{r}
pm25_raw <- read_csv("../data/daily_88101_2023.csv")
o3_raw   <- read_csv("../data/daily_44201_2023.csv")
no2_raw  <- read_csv("../data/daily_42602_2023.csv")

clean_pollutant <- function(df, pollutant_name) {
  df %>%
    filter(`City Name` %in% cities) %>%          # filter ROWS by city name
    mutate(Date = ymd(`Date Local`)) %>%         # convert date
    select(`City Name`, Date, `Arithmetic Mean`) %>%  # select correct columns
    rename(
      City = `City Name`,
      !!pollutant_name := `Arithmetic Mean`
    )
} 

pm25 <- clean_pollutant(pm25_raw, "PM25")
o3   <- clean_pollutant(o3_raw,   "O3")
no2  <- clean_pollutant(no2_raw,  "NO2")

air_df <- pm25 %>%
  inner_join(o3, by = c("City", "Date")) %>%
  inner_join(no2, by = c("City", "Date"))

# There are duplicate rows as the indicators have multiple monitoring sites per city. 
air_df_clean <- air_df %>%
  group_by(City, Date) %>%
  summarise(
    PM25 = mean(PM25, na.rm = TRUE),
    O3   = mean(O3,   na.rm = TRUE),
    NO2  = mean(NO2,  na.rm = TRUE),
    .groups = "drop"
  ) %>%
  arrange(City, Date)

head(air_df_clean)
```